baseurl = "http://gophers.lt"
languageCode = "en-us"
title = "Golang user group"
copyright = "Copyright (c) 2015, gophers.lt; all rights reserved."
MetaDataFormat = "yaml"

[Author]
    name = "DATA-DOG team"
